### PR TITLE
Improve adapter scaling formula

### PR DESCRIPTION
**Pull request by hev**
Addresses #13.

### CODE REVIEW

**Review by johannaratliff — CHANGES_REQUESTED** [review]
A few spelling mistakes here and I changed a few semantic things that don't matter: 

This component manages the connections to external log storage systems and enforces a hard limit of 500 streams. Each syslog-drain creates 2 streams to provide a highly available stream distribution. Therefore we recommend the following metric and formula to determine number of adapters and allow headroom for new bindings.

**Review by johannaratliff — COMMENTED** [review]
Is `cf-syslog-drain.scheduler.drains` the right metric? I can't find it anywhere in the release.
1. Most start with `scalablesyslog.scheduler`
1. There doesn't seem to be a drains count within the spec. May we try and keep it more generic with "# of cf-syslog-drains"

**Comment by hev** [comment]
@JohannaSmith it appears we are not matching our SourceID and Origin on this metric. It appears both as.

`cf-syslog-drain.scheduler.drains` in v1 and `drain_scheduler.drains` in v2

I will file an issue for this separately.

**Comment by hev** [comment]
Filed #15 relating to some confusion around the metric name. Merging this in otherwise.

**Comment by scottillogical** [comment]
@ahevenor not sure if this is indeed an issue otherwise i can create a separate issue, 
```Num of Adapters = (cf-syslog-drain.scheduler.drains / 250) + 2```
Are we sure it's +2 not *2?   I thought the it would be *2 since there are two drains per drain.

**Comment by johannaratliff** [comment]
@scottillogical I believe it refers to the minimum of 2 adapters in order to have drains (e.g. if you have 100 drains, you should still have 2 adapters - accurate based on that equation).

**Comment by jtuchscherer** [comment]
It is indeed + 2. We already factored in the two adapters per drain by dividing the number of drains served by an adapter (500) by 2. You want to have two extra adapters to serve new drains that are created. And also @johannaratliff is correct. You need an minimum of 2 adapters.

**Pull request merged**
